gui:
  nerdFontsVersion: '3'
  sidePanelWidth: 0.3333
  expandFocusedSidePanel: true
  commitAuthorShortLength: 10
  filterMode: fuzzy
  mainPanelSplitMode: horizontal
  theme:
    activeBorderColor:
      - '#f38ba8'
      - bold
    inactiveBorderColor:
      - '#a6adc8'
    optionsTextColor:
      - '#89b4fa'
    selectedLineBgColor:
      - '#313244'
    cherryPickedCommitBgColor:
      - '#45475a'
    cherryPickedCommitFgColor:
      - '#f38ba8'
    unstagedChangesColor:
      - '#f38ba8'
    defaultFgColor:
      - '#cdd6f4'
    searchingActiveBorderColor:
      - '#f9e2af'
os:
  editPreset: 'nvim'

