return {
  {
    'mason-org/mason.nvim',
    event = 'VeryLazy',
    opts = {
      ui = {
        icons = {
          package_installed = '✓',
          package_pending = '➜',
          package_uninstalled = '✗',
        },
        border = 'rounded',
      },
    },
  },
  {
    'mason-org/mason-lspconfig.nvim',
    event = 'VeryLazy',
    opts = {
      ensure_installed = {
        'clangd',
        'cssls',
        'docker_compose_language_service',
        'dockerls',
        'eslint',
        'gopls',
        'harper_ls',
        'helm_ls',
        'html',
        'jdtls',
        'jsonls',
        'lua_ls',
        'marksman',
        'nginx_language_server',
        'pyright',
        'ruff',
        'ts_ls',
        'vtsls',
        'vue_ls',
        'vuels',
        'yamlls',
      },
    },
  },
  {
    'WhoIsSethDaniel/mason-tool-installer.nvim',
    cmd = 'MasonToolsInstall',
    opts = {
      ensure_installed = {
        'cpptools',
        'eslint_d',
        'gofumpt',
        'goimports',
        'goimports-reviser',
        'golangci-lint',
        'gomodifytags',
        'google-java-format',
        'hadolint',
        'java-debug-adapter',
        'java-test',
        'jsonlint',
        'markdown-toc',
        'markdownlint-cli2',
        'prettier',
        'pyproject-fmt',
        'shfmt',
        'sonarlint-language-server',
        'stylua',
        'tombi',
        'tree-sitter-cli',
      },
      integrations = {
        ['mason-lspconfig'] = true,
      },
    },
  },
}
